spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        query.in_clause_parameter_padding: true
        storage_engin: innodb
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
