spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL


  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        query.in_clause_parameter_padding: true
        storage_engin: innodb
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
#  sql:
#    init:
#      platform: h2
#      data-locations: classpath:sql/data_new.sql
#      encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8

cloud:
  aws:
    credentials:
      accessKey: AKIASRDLDX3THKA3JQOP
      secretKey: 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
    s3:
      bucket: team15-image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false