# https://github.com/appleboy/ssh-action

name: Github Action(Shell) to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release/*, develop]

jobs:
  build:
    name: Github Action to EC2
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./deploy.sh
